title: SmartPay
email: contact@example.gov
description: >- # this means to ignore newlines
  Established in 1998, the GSA SmartPay Program is the world’s largest government charge card and commercial payment solutions program, providing services to more than 560 federal agencies, organizations, and Native American tribal governments.

host: https://smartpay.gsa.gov/

# Twitter handle. Only the handle, not the URL.
twitter: GSASmartPayNews

#################################################################
#
# Digital Analytics Program (DAP) configuration
#
# USAID   - Agency for International Development
# USDA    - Department of Agriculture
# DOC     - Department of Commerce
# DOD     - Department of Defense
# ED      - Department of Education
# DOE     - Department of Energy
# HHS     - Department of Health and Human Services
# DHS     - Department of Homeland Security
# HUD     - Department of Housing and Urban Development
# DOJ     - Department of Justice
# DOL     - Department of Labor
# DOS     - Department of State
# DOI     - Department of the Interior
# TREAS   - Department of the Treasury
# DOT     - Department of Transportation
# VA      - Department of Veterans Affairs
# EPA     - Environmental Protection Agency
# EOP     - Executive Office of the President
# GSA     - General Services Administration
# NASA    - National Aeronautics and Space Administration
# NARA    - National Archives and Records Administration
# NSF     - National Science Foundation
# NRC     - Nuclear Regulatory Commission
# OPM     - Office of Personnel Management
# USPS    - Postal Service
# SBA     - Small Business Administration
# SSA     - Social Security Administration
#
#################################################################
dap:
  # agency: your-agency

  # Optional
  # subagency: your-subagency

# Configuration for Google Analytics
ga:
  # ua: your-ua

# Site Navigation
primary_navigation:
  - name: News
    url: /blog/ 
  - name: Account Holders & Approving Officials
    children:
      - name: Purchase
        url: "#main-content"
      - name: Travel
        url: "#main-content"
      - name: Fleet
        url: "#main-content"
      - name: Integrated
        url: "#main-content"
      - name: Training
        url: "#main-content"
      - name: Guides, Presentations & Publications
        url: "#main-content"
      - name: Fraud Prevention
        url: "#main-content"
      - name: Common Questions
        url: "#main-content"                          
  - name: Program Coordinators
    children:
      - name: Purchase
        url: "#main-content"
      - name: Travel
        url: "#main-content"
      - name: Fleet
        url: "#main-content"
      - name: Integrated
        url: "#main-content"
      - name: Training for A/OPCs
        url: "/online-training-aopcs/"
      - name: Guides, Presentations & Publications
        url: "#main-content"
      - name: Audit Repository
        url: "#main-content"
      - name: Fraud Prevention
        url: "#main-content"
      - name: Common Questions
        url: "#main-content"                
  - name: Business & Vendors
    children:
      - name: GSA SmartPay for Vendors
        url: "#main-content"
      - name: Recognizing the GSA SmartPay Account
        url: "#main-content"
      - name: Guides, Presentations & Publications
        url: "#main-content"
      - name: Vendor Common Questions
        url: "#main-content"        
  - name: About
    children:
      - name: The GSA SmartPay Program
        url: /about/
      - name: Master Contract
        url: /gsa-smartpay-master-contract/
      - name: Statistics
        url: "#main-content"
      - name: Policies
        url: "#main-content"
      - name: SmartTax
        url: "/smarttax/"
      - name: State / Local Government
        url: "#main-content"
      - name: Strategic Payment Solutions
        url: "#main-content"
      - name: Logos & Designs
        url: "#main-content"
      - name: Glossary
        url: "#main-content"         

secondary_navigation:
  - name: Visit Online Training
    url: https://training.smartpay.gsa.gov/
  - name: Contact Us
    url: "#main-content"

side_navs:
  - name: smarttax
    header_text: SmartTax
    parent_url: /smarttax/
    children:
      - text: About SmartTax
        url: /smarttax/about-smarttax/
      - text: Legal History
        url: /smarttax/legal-history/
      - text: Recognizing Your Account
        url: /smarttax/recognizing-your-account/
      - text: FAQs
        url: /smarttax/faqs/
      - text: State Tax Information
        url: /smarttax/state-tax-information/
      - text: Surcharges
        url: /smarttax/surcharges/

  - name: about
    header_text: About
    parent_url: /smarttax/
    children:
      - text: About SmartTax
        url: /smarttax/about-smarttax/
    

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:

  # Only change this if you're using a CNAME. Learn more here: https://search.gov/manual/cname.html
  endpoint: https://search.usa.gov

  # Replace this with your search.gov account.
  affiliate: federalist-uswds-example

  # Replace this with your access key.
  access_key: xX1gtb2RcnLbIYkHAcB6IaTRr4ZfN-p16ofcyUebeko=

  # This renders the results within the page instead of sending to user to search.gov.
  inline: true

  # This allows Search.gov to present relevant type-ahead search suggestions in your website's search box.
  # If you do not want to present search suggestions, set this value to false.
  suggestions: true

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################
