# This workflow will do a clean install of node dependencies, build the source code and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Accessibility Tests

on:
  push:
    branches: # Run actions when code is committed to these branches
      - main
  pull_request:
    branches: # Run actions when a PR is pushed based on one of these branches
      - main
      - staging
jobs:
  accessibility_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from ${{ github.repository }}
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Run pa11y 
        run: npm run pa11y-ci:gh 